# Generated by Django 5.0.1 on 2024-03-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carpost',
            old_name='name',
            new_name='tittle',
        ),
    ]
