# Generated by Django 5.0.1 on 2024-03-01 07:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0002_rename_name_carpost_tittle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CarPost',
            new_name='Post',
        ),
    ]
