# Generated by Django 5.0.1 on 2024-03-01 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='car', to=settings.AUTH_USER_MODEL),
        ),
    ]
